###
GET http://localhost:8080/store/all HTTP/1.1

###
POST http://localhost:8080/store/addNewStore HTTP/1.1
Content-Type: application/json

{
   "user" : {"id" : 252},
   "game" : {"id" : 152}
 }

###
PUT http://localhost:8080/store/updateStore HTTP/1.1
Content-Type: application/json

{
    "user" : {"id" : 1},
    "game" : {"id" : 1}
}


###
DELETE http://localhost:8080/store/deleteStore/804 HTTP/1.1

###
GET http://localhost:8080/store/user?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKdWxpYSIsImVtYWlsIjoianVsaWFASnVsaWEuY29tIiwiaWQiOiIxIiwiaWF0IjoxNzMzMjQyMjc4LCJleHAiOjE3MzMzMjg2Nzh9.YZulrx_EpBaPVabV9V1WUdiRW8cLmNcrsHQ6cdF_15k HTTP/1.1
